my-sql:
  host: 'localhost'
  port: 3306
  data-base: 'data-base-name'
  status-table: 'table-name'
  equipment-table: 'equipment-table'
  user: 'user'
  password: 'password'

join-location: 'world, 0.0, 0.0, 0.0'
lobby-location: 'world, 0.0, 0.0, 0.0'